### ISSUE TITLE
Runtime misplacement

### ISSUE THREAD

**Issue by RomRider** [kalkih/mini-media-player#119]
Hey,

It appears that there's a slight glitch with the runtime placement (currently using Chrome both desktop and android). Also when the runtime is not displayed, the progress is kind of _dimmed_
* `hide.runtime: false`
![image](https://user-images.githubusercontent.com/21064206/57580917-21b3ac00-74b0-11e9-9d86-31f51a2d65ba.png)
* `hide.runtime: true`
![image](https://user-images.githubusercontent.com/21064206/57580966-db128180-74b0-11e9-9c68-6ca7ad9dfbe5.png)

Here's my config:
```yaml
      type: custom:mini-media-player
      entity: media_player.sonos_universal
      name: Sonos Connect
      artwork_border: true
      icon: mdi:disc-player
      hide:
        name: true
        icon: true
        power: true
        volume: false
        shuffle: false
        source: true
        progress: false
        runtime: false/true
      artwork: full-cover
      group: false
      max_volume: 80
```

**Comment by kalkih** [comment]
Hey, should be fixed with 3853729ae4911fe1aac3ce09b2ad821bf1a1192b
Will be included in the next release.

**Comment by RomRider** [comment]
Amazing, thanks :)

**Comment by RomRider** [comment]
I've tested the `dev` branch and it seems the runtime is still a bit off compared to when the artwork in not in `full-cover` mode:
![image](https://user-images.githubusercontent.com/21064206/57583243-ca710400-74ce-11e9-89f1-76c13d9e7dad.png)

**Comment by kalkih** [comment]
Strange, tried with your config, should be fixed in the latest release, give it a shot!

**Comment by RomRider** [comment]
@kalkih, still the same issue as my last comment with 1.1.3 :( Running latest chrome desktop, same on android.

**Comment by kalkih** [comment]
Okay I found the issue..., If the active theme didn't have `--ha-card-border-radius` set, the style would fallback to an invalid value because I missed putting `px` after `4` 😞 

Anyway, setting `--ha-card-border-radius: 0px` should solve the issue until the next release, or if you want to build from source.

**Comment by RomRider** [comment]
Great, it's working, I built from source! Thanks a lot :)

**Comment by kalkih** [comment]
Fix now available in the latest release :tada:
