### ISSUE TITLE
Seems like latest update broke source dropdown

### ISSUE THREAD

**Issue by estiens** [kalkih/mini-media-player#203]
Source always appears below whatever cards are underneath it.

<img width="350" alt="Screen Shot 2019-12-16 at 10 47 59 AM" src="https://user-images.githubusercontent.com/4022668/70925852-98d69300-1ff1-11ea-9264-d6a45e27519f.png">
<img width="661" alt="Screen Shot 2019-12-16 at 10 47 41 AM" src="https://user-images.githubusercontent.com/4022668/70925853-98d69300-1ff1-11ea-92ac-edc8003e7345.png">

**Comment by kalkih** [comment]
Thanks, duplicate of https://github.com/kalkih/mini-media-player/issues/201, will roll out a new minor release later tonight with this addressed.

**Comment by kalkih** [comment]
Fixed in the latest release, thanks!
I like your theme, looks cool! 🙂

**Comment by estiens** [comment]
<img width="602" alt="Screen Shot 2019-12-16 at 5 39 16 PM" src="https://user-images.githubusercontent.com/4022668/70952160-136fd480-202b-11ea-808a-d2069a7477ac.png">

Still seeing this here with latest release after refresh? I can play with it a bit on this end as well and see if I can narrow it down.

**Comment by kalkih** [comment]
Try clearing cache, and if using HACS reinstalling the card.

**Comment by jonostanck** [comment]
Don't know why and exactly when it started but it's happening again... is it only me?
![image](https://user-images.githubusercontent.com/33318513/78504829-b03bb680-776f-11ea-9934-cb0ab1e9aa04.png)
I've tried to alter this by changing styles but nothing seems to work...

**Comment by jonostanck** [comment]
OK, debugged this issue and it's happening when mini-media-player is used in conjunction with (within) state-switch custom card. Just to let you know @kalkih these two are not working together nicely.
