### ISSUE TITLE
Dropdown menu won´t work on Iphone with Home Assistant app 2.0 

### ISSUE THREAD

**Issue by lindberg87** [kalkih/mini-media-player#207]
Hey I have a Issue with the mini media player, on my Iphone I can´t control the drop down menu to choose a radio channel, there nothing happens then I press the radio channel I want to listing to. If I go to home assistant frontend at my computer, the mini media player works fine, there is no problems with the drop down menu. 

Hope it will be fixed in the future. 

Best Regards Stig

**Comment by kalkih** [comment]
Hey,
Alright, I'll see if I can replicate the issue and fix it.

Does the dropdown close when you press an entry or does it stay open?
Also, what iOS version are you running? Is this in Safari or in the official HA app or in another browser?

Thanks!

**Comment by mihalski** [comment]
I'm not sure if my problem is related or not but for me the menu renders underneath the card below it like so in Chromium based browsers:
![image](https://user-images.githubusercontent.com/3755059/71646471-e282e580-2d34-11ea-897f-4bf4ec1bc31f.png)
And like so in the iPhone iOS app:
![image](https://user-images.githubusercontent.com/3755059/71646496-5c1ad380-2d35-11ea-929f-5eca3d4c9227.png)

**Comment by kalkih** [comment]
Could be related, the issue where the dropdown is rendered below the card was fixed in the latest update (v1.5.1), try updating to that version if you haven't already.

Although I saw some users reporting issues with the cache not clearing properly with HACS, resulting in the client not loading the latest version of the card and the issue remains. Uninstalling and reinstalling the card could solve that.

If you've installed the card manually, simply adding `?v=1.5.1` at the end of the mini-media-player resource url in your config should force the client to load the new version.

**Comment by lindberg87** [comment]
I have tried to uninstalled and reinstall the v1.5.1 and the problem is still there. I can open the drop down menu and choose a radio channel and the drop down menu closes and nothing happens. 
If I do the same via chrome browser on my pc it work super perfect. 
The problem started for me after mini player got update to v1.4.0

**Comment by mihalski** [comment]
I do use HACS and i just uninstalled, reinstalled, added to lovelace using HACS and now it works!

**Comment by kalkih** [comment]
> I have tried to uninstalled and reinstall the v1.5.1 and the problem is still there. I can open the drop down menu and choose a radio channel and the drop down menu closes and nothing happens.
> If I do the same via chrome browser on my pc it work super perfect.
> The problem started for me after mini player got update to v1.4.0

Okay, thanks for the info, I'll check tomorrow, do you know what version of iOS you're on?

> I do use HACS and i just uninstalled, reinstalled, added to lovelace using HACS and now it works!
> 
> EDIT: And it works in both Chromium based browsers and in the iOS app.

Perfect 👍

**Comment by lindberg87** [comment]
Hey Kalkih I´m running iOS 13.3 os iPhone xs max

**Comment by kalkih** [comment]
@lindberg87 Thanks, I was able to reproduce it in the latest iOS app, tried rolling back to an older version of the mini-media-player card, all the way back to 1.0.0 but the issue remained on all versions.

So most likely something changed with the iOS app because I know it was working before.

Will fix asap, thanks

**Comment by deluxestyle** [comment]
Have the same issue not only on ios as well on Windows and Chrome

**Comment by lindberg87** [comment]
@kalkih Thank you very much :)

**Comment by kalkih** [comment]
> Have the same issue not only on ios as well on Windows and Chrome

@deluxestyle Which one, dropdowns rendering behind cards or that nothing happens when you press an item?

**Comment by deluxestyle** [comment]
Oh sorry. Dropdowns behind cards.

**Comment by kalkih** [comment]
@deluxestyle That was fixed in the latest release #201

**Comment by deluxestyle** [comment]
@kalkih reinstalled with HACS and it seems to work now. maybe it was still chached

**Comment by kalkih** [comment]
Should now be working as expected again in the latest release [v1.5.2](https://github.com/kalkih/mini-media-player/releases/tag/v1.5.2).

Thank you!

**Comment by lindberg87** [comment]
Kalkih Sorry to open this quote again, I just need to say thank you very much for your hard work on the update to mini player, the problem is now gone and solve  :) 
Best Regards

**Comment by kalkih** [comment]
That's great to hear, thank you for the feedback, it's always appreciated! 😃
