### ISSUE TITLE
2022.3.X Breaks dropdown

### ISSUE THREAD

**Issue by bramkragten** [kalkih/mini-media-player#606]
mini-media-player uses `paper-menu-button` and `paper-listbox` with the assumption Home Assistant will load these elements.

https://github.com/kalkih/mini-media-player/blob/master/src/components/dropdown.js#L57

In 2022.3 these elements are no longer part of Home Assistant, so this will no longer work.

**Comment by kalkih** [comment]
Thanks for the heads up, much appreciated.
Any suggestions on elements registered by HA to replace them with? or should I move in the direction of bundling my own components with the card?

**Comment by donaldguy** [comment]
Having fallen way too far down a rabbit hole of `impostersyndromedog.png`[^1]  to justify my mere desire to get my dropdown to close (see closed issue just above), I tried to update this repo to Lit 2 and bundle in the needed/existing[^2] polymer components (and then integrated ESM `import` in a vein attempt to de-dupe the imports in the short term):

https://github.com/donaldguy/mini-media-player/commit/d643b8310e1e5eda59b41ebdb60914f675736a29

It will `npm run webpack` "build" (`npm run build` gets tripped up on eslint w/ the `.js`s on the directive imports - without which webpack says it can't find the exports ) 

But (despite it being the same error that motivated my attempt to replatform onto `import` right quick in the first place), this still just gets me: 

>2022-02-17 23:24:28 ERROR (MainThread) [frontend.js.latest.202202140] https://[redacted]/hacsfiles/mini-media-player-card/mini-media-player-bundle.js?v=1eefb224-da69-426d-b6b7-2054dd34b382:1:0 NotSupportedError: CustomElementRegistry.define: 'dom-module' has already been defined as a custom element

(despite the `/hacsfile` there, I am pretty sure this is in fact the new bundle I`scp`ed in and changed the UUID get param of; I deleted the cached version through web tools for good measure)

---

So I give up. Someone who has used any of these technologies before can take a crack at it - I'll swap back to `entities` or maybe downgrade idk.

Hopefully that commit can save you some of the busy work though?

[^1]: <img src="https://user-images.githubusercontent.com/43136/154622822-c3e016eb-cd1b-4508-956f-535441fa1d73.png" width=150>

[^2]: I think the typeaheads on the mwc-select seem nice, but I was trying to _limit_ blast radius

**Comment by Mariusthvdb** [comment]
I guess this is what I am experiencing now: https://github.com/home-assistant/frontend/issues/11738

<img width="509" alt="Schermafbeelding 2022-02-19 om 22 32 21" src="https://user-images.githubusercontent.com/33354141/154820057-3c088fcd-1fcb-4ba7-b7c3-df618564fd1a.png">

**Comment by donaldguy** [comment]
Reverting to my backup at core-2022.3.0.dev20220213 (ghcr.io/home-assistant/qemux86-64-homeassistant@sha256:0a4f7cc00c2664ab8edcab19afe87e2f94584b99453256831cc0bd356c7e0aaf; Frontend version: 20220203.0 - latest) did resolve the issue for me for the time being 

So we can gather the change is somewhere in here:
https://github.com/home-assistant/frontend/compare/20220203.1...20220214.0 

(I mean, it seems like the above explanation could still track, but just saying)

**Comment by donaldguy** [comment]
And I guess this is our template for going forward? https://github.com/home-assistant/frontend/pull/11543/files

**Comment by donaldguy** [comment]
Well more relevantly https://github.com/home-assistant/frontend/pull/11591/files

**Comment by kalkih** [comment]
Hey guys, thanks for the ideas and the discussion.

So I feel like the right thing going forward is to move away from HA defined elements, as using them cause the card to break every now and then.
(I think?) HA also defines some elements in runtime so user's might experience different behaviour depending on setup.

The drawback being the increased bundle size, but since at least the mwc element are built with Lit (which I already bundle with the card), the difference shouldn't be massive.

[Here's a branch](https://github.com/kalkih/mini-media-player/commit/ba4291a47834c5912edf4251e1955f4f6a76fd7d) with `mwc-menu` bundled and with the elements defined under different names to avoid the duplicate elements issue.

It's untested in HA and themeing is probably not working correctly with HA defined variables.
If anyone want to test it out and/or continue to tweak it, please do.

**Comment by donaldguy** [comment]
No dice on the branch as yet:

```
2022-02-22 14:12:09 ERROR (MainThread) [frontend.js.latest.202202200] /hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381151:1:0 NotSupportedError: CustomElementRegistry.define: 'mmp-checkbox' has already been defined as a custom element
2022-02-22 14:12:15 ERROR (MainThread) [frontend.js.latest.202202200] /hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381151:1:0 NotSupportedError: CustomElementRegistry.define: 'mwc-ripple' has already been defined as a custom element
```

Not immediately sure how hard/possible it is to shadow out those sub-elements too.

---
I do (still) suspect tho that it would be okay to both ship the mwc components (so you are _sure_ you can depend on them) and also, in practice, preferentially import the HA-shipped versions (avoiding the double def), using new-fangled module/manifest dynamic import, but I admit I don't fully understand how that (would) work/s

(and the impression that it can work may be informed by looking in devtools at a less-productionized webback build on the core frontend that's potentially an artifact of pulling dev channel builds)

**Comment by kalkih** [comment]
> I do (still) suspect tho that it would be okay to both ship the mwc components (so you are sure you can depend on them) and also, in practice

That's exactly what I did with `mwc-menu` and `mwc-list-item` in that branch, I extend the base classes of those components and define the elements with my custom names so they won't clash with the mwc elements defined by HA.
Altough if these components have other mwc-components as dependecies I'm not sure if this is a viable approach anyway.

https://github.com/kalkih/mini-media-player/commit/ba4291a47834c5912edf4251e1955f4f6a76fd7d#diff-0d1e9e111ee4cf01c8b8f80f8a4e0e2fd735e4ae2e82abf2bf8c24f840791e5aR11-R24

The first error you posted seems strange though, `mmp-checkbox` should for sure not be defined more than once, make sure you're not loading `mini-media-player` multiple times, e.g. multiple resource references to `mini-media-player` in your setup.

**Comment by bramkragten** [comment]
Here is an example how `mwc` elements can be used in custom cards in the next Home Assistant version:

https://github.com/custom-cards/boilerplate-card/pull/50/files

**Comment by bramkragten** [comment]
Or a simpler example here:

https://github.com/piitaya/lovelace-mushroom/issues/133#issuecomment-1047826814

We are shipping the [scoped-custom-element-registry polyfill](https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry) with the next HA release

**Comment by kalkih** [comment]
Thanks @bramkragten,

Might not be an issue, haven't read up on the Scoped Custom Element Registries spec fully yet.
But will we not potentially still have issues when mwc-elements are imported in the base classes of the mwc-elements? Such as here
https://github.com/material-components/material-web/blob/master/packages/list/mwc-check-list-item-base.ts#L11

**Comment by hmmbob** [comment]
Can confirm this card is broken on 2022.3:

![image](https://user-images.githubusercontent.com/33529490/156128295-83a93014-22f3-4db3-8886-5a44c342cf7b.png)

**Comment by bramkragten** [comment]
> Thanks @bramkragten,
> 
> Might not be an issue, haven't read up on the Scoped Custom Element Registries spec fully yet. But will we not potentially still have issues when mwc-elements are imported in the base classes of the mwc-elements? Such as here [https://github.com/material-components/material-web/blob/master/packages/list/mwc-check-list-item-base.ts#L11](https://github.com/material-components/material-web/blob/master/packages/list/mwc-check-list-item-base.ts?rgh-link-date=2022-02-25T17%3A52%3A51Z#L11)

That's why we also define those, and ignore those imports in the rollup config.

So it needs some "hacks", but it works...

**Comment by kalkih** [comment]
Until I've bundled the mwc-elements with the card this fix should do: #616

Beta release here:
https://github.com/kalkih/mini-media-player/releases/tag/v1.16.0-beta

Let me know

**Comment by hmmbob** [comment]
Jep, beta fixes the issue for me

**Comment by hmmbob** [comment]
Jep, beta fixes the issue for me

![Screenshot_20220302-191046_Home Assistant](https://user-images.githubusercontent.com/33529490/156422592-fdfe31bc-7daf-4208-b137-79478a8d632f.jpg)
![Screenshot_20220302-191032_Home Assistant](https://user-images.githubusercontent.com/33529490/156422597-71fb7015-a517-4805-80b8-57188942b553.jpg)

**Comment by tomlut** [comment]
Delete the .gz file

**Comment by vadimbz** [comment]
Reinstalling from HACS worked, thanks!

**Comment by niekniek89** [comment]
upgrading to beta version fixed the issue!

**Comment by pepsonEL** [comment]
Update to 2022.3 for me some breaks card....
source from media player fix show on other entity....
![screen](https://user-images.githubusercontent.com/71824185/156549016-97c2c5d6-3630-4f3d-9cc5-b58a302cd2ab.jpg)

**Comment by kalkih** [comment]
Fix now also available in latest stable release.

**Comment by 03397** [comment]
I have upgraded the  actual problem is solved  but not another problem arose. I can  see the listing on the first player but 
on the second media player I cannot see the listing(on my mobile phone home assistant app) 
cards:
  - entity: media_player.sonos_one
    hide:
      info: false
      power: true
      runtime: false
      shuffle: false
    info: scroll
    name: Master Bedroom
    type: custom:mini-media-player
    group: false
  - entity: media_player.sonos_one
    hide:
      controls: true
      icon: true
      info: true
      name: true
      power: true
      progress: true
      source: true
      volume: true
    volume_stateless: true
    type: custom:mini-media-player
    source: full
    sound_mode: full
    artwork: full-cover
    group: false
type: vertical-stack

**Comment by tnagels** [comment]
v16 which was just released does not solve the problem for me; drop-downs in the card config do not work.

**Comment by hmmbob** [comment]
Try clearing your cache

**Comment by tnagels** [comment]
I did that. I'm seeing the same behaviour on Chrome, Edge & the HA app. HA has been restarted and the caches cleared.

**Comment by 03397** [comment]
Guys this solves the issue for me but sometimes it is giving me error saying
https://xxxxxxxxxzzzz/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381160:1:154147 Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '#9bpap80z7-menu' is not a valid selector.

**Comment by MarcelS1988** [comment]
On chrome the problem is solved, but on IOS and Android tablet with fully kiosk still the same problem.

**Comment by hmmbob** [comment]
Highly likely a caching issue?

**Comment by MarcelS1988** [comment]
On IOS you can not clear the caching? On Tablet I have done it but still it will not work. Or if you have any other ideas?

**Comment by stronheim** [comment]
> Delete the .gz file
> 
> You can install beta versions with HACS. just tick the beta versions box.

Where do you find the .gz file to delete it?

I've updated the the beta and the problem is persisting for me.

**Comment by hmmbob** [comment]
You don't need the beta, just upgrade the card through HACS and _clear caches_

**Comment by stronheim** [comment]
> You don't need the beta, just upgrade the card through HACS and _clear caches_

I've done the upgrade and cleared the caches on my phone and my pc and the problem is persisting. Can't quite work out why it's persisting

**Comment by MarcelS1988** [comment]
Here the update works on the pc but not on android tablet and IPhone

Verstuurd vanaf mijn iPhone

> Op 11 mrt. 2022 om 15:04 heeft stronheim ***@***.***> het volgende geschreven:
> 
> I've done the upgrade and cleared the caches on my phone and my pc and the problem is persisting. Can't quite work out why it's persisting

**Comment by alex-gillies** [comment]
This is my configuration UI in version 1.16.1, HA 2022.4.7, Chrome 101.0.4951.41.
I've cleared cache, restarted HA and host, hard refreshed, reinstalled HACS and Mini Media Player. Apologies if I'm missing something in troubleshooting, but I'm kind of at a loss at this point. I'm able to work around it with the code editor but would really like to get this fixed if possible.

Any advice would be greatly appreciated

![ConfigUI](https://user-images.githubusercontent.com/32212151/166119636-00c2eb2b-617b-493a-bdde-ed6028c8a53d.png)

**Comment by kalkih** [comment]
@alex-gillies For some reason the minor releases of the card seems to unpublish themselves on github...
I've republished the latest version (1.16.2), Check for this version in HACS, this version should include fixes for the issues you're seeing.

**Comment by alex-gillies** [comment]
@kalkih Fixed! Thanks for the quick turnaround!
